pearu/pylibtiff

libtiff/libtiff_ctypes.py

Here are a couple of patches that should improve a little the code for the libtiff wrapper. 
(I had send them a while ago by email, but it's probably easier for merging to do it via a pull request).
- The first patch ensures that when compression is None, it's correctly converted to COMPRESSION_NONE for the calls to libtiff.
- The second patch enforces the use of predictor when using compression (and a data type that supports a predictor). That allows a better compression ratio with most data (without changes in the client code).
- The thirds patch is just cosmetic, and removes the use of "exec", which is not recommended to use in Python.

Small improvements on ctypes libtiff wrapper code

---

libtiff/libtiff_ctypes.py

Previous commit  030e2979, reverting back the method names to CamelCase, was not sufficiently tested. It introduced some typos, which prevented the whole module to load.

ctypes wrapper: fix some method names

---

libtiff/optparse_gui.py

The update to make it working on Python 3 broke it for Python 2.
Luckily, importing changes from the __future__ fixes it.

optparse_gui: fix for Python 2

---

libtiff/libtiff_ctypes.py

We want to be able to read/write "pyramidal images" (as described [here](http://iipimage.sourceforge.net/documentation/images/)). In order to support this format we need two features not provided by the ctypes wrapper: sub-directory access, and access to one tile at a time.
This pull-request addresses these needs. Note that for proper pyramidal images support (and for the test-cases to pass), the PR #57 is also needed.
It's been tested with libtiff 3.95, and 4.0.6, on Ubuntu 32 bits and 64 bits, and Windows 32 bits.

Extend tile and sub-directory support

---

libtiff/libtiff_ctypes.py

We need to save (and read back) the tags EXTRASAMPLES and SUBIFD. These tags were not supported, because they are variable length. So we add support for such tags.
The functions also had a couple of issues in corner-cases, which we encountered after using pyliftiff a little intensively. This pull-request also brings fixes for these issues.

Fix and improvements for GetField/SetField

---

libtiff/libtiff_ctypes.py

The changes to support Python 3 forced the filename to be explicitly encoded.
However, the encoding was hard-coded to "ascii", which prevents any file with
non-ascii character to be opened.
For instance, a file named "tést.tiff" couldn't be opened anymore.

ctypes wrapper: fix opening files with names containing non-ascii characters

---

libtiff/bitarray-0.3.5-numpy/bitarray/test_bitarray.py
libtiff/bitarray-a1646c0/bitarray/__init__.py
libtiff/bitarray-a1646c0/bitarray/test_bitarray.py
libtiff/setup.py

1. Change importing of bitarray in ``bitarray/__init__.py`` to use relative path
2. Replaced remaining explicit uses of ``it.__next__`` with uses of ``next(it)``
3. For py2.7 use with ``self.assertRaises(errclass): statement`` rather than
``self.assertRaises(errclass, statement)``
py26 still uses the older formulation.

Fixed tests to pass with python 2.7

---

libtiff/libtiff_ctypes.py

If libtiff fails to read a strip (indicated by returning -1), raise an exception instead of moving the data buffer position backwards.

Raise an exception if ReadStrip returns -1.

---

libtiff/libtiff_ctypes.py

Try to load `libtiff` through other methods if `ctypes.util.find_library` fails completely (was PR36)

---

libtiff/tiff_file.py

To allow the user to filter warnings, use the warnings.warn function
instead of directly outputting to stderr.
This is a second try of #43.
Sorry for the non-semantic changes.

Warning instead of sys.stderr.write

---

libtiff/libtiff_ctypes.py

Without this fix the following error occurs:
```
('__attribute__((deprecated))', '#define TIFF_GCC_DEPRECATED __attribute__((deprecated))\n') name '__attribute__' is not defined
Traceback (most recent call last):
File "/home/bob/git/pylibtiff/./test.py", line 3, in <module>
import libtiff
File "/home/bob/git/pylibtiff/libtiff/__init__.py", line 23, in <module>
from .libtiff_ctypes import libtiff, TIFF, TIFF3D  # noqa: F401
File "/home/bob/git/pylibtiff/libtiff/libtiff_ctypes.py", line 127, in <module>
value = eval(value)
File "<string>", line 1, in <module>
NameError: name '__attribute__' is not defined
```

Ignore deprecation defines added in tiff 4.3 headers.

---

libtiff/libtiff_ctypes.py

Some time ago, the GnuWin32 project provided Windows builds of libtiff, under the filename libtiff3.dll. The last version was 3.8.2, in 2006. The more recent versions of libtiff (v4+) are built as libtiff.dll.
Some customers were not able to run our application, although we ship the latest version of libtiff.dll with it. It turned out that they have an old 32-bit version of libtiff3.dll somewhere else on their system. This made LoadLibrary fail with such (confusing) error message: "Failed to load dynlib/dll 'C:\\GTK\\bin\\libtiff3.dll'. Most probably this dynlib/dll was not found when the application was frozen."
=> Change the order of DLL search to first look for the recent version, and fallback to the ancient libtiff3.

libtiff_ctypes: search first for libtiff.dll before libtiff3.dll

---

libtiff/libtiff_ctypes.py

Closes #134. `numpy.bool` is being deprecated in numpy and will result in an AttributeError if used from now on. This PR replaces the usage with `np.bool_` which is supported and seems to work.
CC @mraspaud @gerritholl @talonglong

Fix compatibility with newer numpy (np.bool_)

---

MANIFEST.in

The conda-forge build revealed that the sdist was missing the README.md file so `setup.py` was failing.

Add missing README.md to sdist

---

libtiff/libtiff_ctypes.py

* The default name of the shared library on Windows is `tiff.dll` in recent libtiff.
* `ctypes.util.find_library` takes library names without any suffix.
*  Add `libtiff_version_tuple`.
* `tdir_t` is defined as `uint32_t` in libtiff >= 4.5.0.
* `tsize_t` is defined as `SSIZE_T`.
See also https://gitlab.com/libtiff/libtiff/-/blob/v4.5.0/libtiff/tiffio.h#L65-77
Tested on Python 3.11 64-bit on Windows 10 with libtiff 4.5.0.

Various ctypes fixes

---

pyproject.toml

setuptools_scm_git_archive has been deprecated for a long time. The new version of setuptools_scm (8+) makes incompatible changes that break building for all packages using the deprecated git archive package. This updates pylibtiff to use the new versions of stuff.

Update to new setuptools_scm and remove deprecated setuptools_scm_git_archive

---

.github/workflows/ci.yaml
README.md
libtiff/script_options.py

Replaces #164. This also drops a `wx` import in addition to dropping the `matplotlib` import we talked about in #164. @pearu thoughts?
CC @dennis-johnson

Change matplotlib backend to GTk3Agg for POSIX

---

libtiff/libtiff_ctypes.py
libtiff/lsm.py

When the module is embedded in a executable (aka "frozen"), the __file__ path is virtual, and might not actually exists on the computer. This path is used at init to look for the DLL, by changing the current working directory to the containing folder. As it doesn't exist, it fails, and libtiff_ctypes cannot be imported.
Instead of completely failing, now handle such case, and just don't use that folder as an extra location to look for the DLL.

ctypes: don't fail to load when embedded as a "frozen" package

---

.github/workflows/ci.yaml
libtiff/libtiff_ctypes.py
libtiff/tests/test_libtiff_ctypes.py

- **fix: declare argtypes for non-variadic arguments Closes #178**
- **Reenable mac CI tests**
- **Unwrap ctypes data types when passing them as variadic arguments**
In #179, the error `ffi_prep_cif_var failed` was reported when passing a ctypes data type as a variadic argument.
Here we unwrap the ctypes data type which no longer produces an error.
This appears to a problem with how ctypes uses libcffi, but it will require further investigation in cpython. For now, this works.
Added low-level (`TIFFSetField`, `TIFFGetField`, `TIFFGetFieldDefaulted`) and high-level tests (`TIFF.SetField`, `TIFF.GetField`) for `uint16`, `uint32`, `float`, `double`, `string`, and arrays (e.g. colormap).

fix: declare argtypes for non-variadic arguments, part 2

---

.github/workflows/ci.yaml
libtiff/libtiff_ctypes.py

Closes #178
This declares the non-variadic arguments for SetField and GetField, which is needed on ARM64 due to ABI differences (see issue #178 for discussion). This should not impact compatibility with other architectures.

fix: declare argtypes for non-variadic arguments
